# group_attributes

In [1]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook(db_type="sqlite", db_name="group_attribute")

In [2]:
# NBVAL_IGNORE_OUTPUT
import timelink

tlnb.print_info()
timelink.version

Project name: test-project
Project home: /Users/jrc/develop/timelink-py/tests/timelink-home/projects/test-project
Database type: sqlite
Database name: group_attribute
Kleio image: timelinkserver/kleio-server
Kleio server token: l4cIJ...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/develop/timelink-py/tests/timelink-home/projects/test-project
Kleio server container: elegant_bhabha
Kleio version requested: latest
Kleio server version: 12.5.570 (2024-02-29 07:39:03)
SQLite directory: /Users/jrc/develop/timelink-py/tests/timelink-home/projects/test-project/database/sqlite
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=test-project, project_home=/Users/jrc/develop/timelink-py/tests/timelink-home/projects/test-project, db_type=sqlite, db_name=group_attribute, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

'1.1.6'

In [3]:
### Import file
from timelink.api.database import import_from_xml

db = tlnb.db
with db.session() as session:
    import_from_xml( "../../../../xml_data/dehergne-a.xml",session)

In [4]:
from timelink.pandas.group_attributes import group_attributes
from timelink.pandas import entities_with_attribute

# Get list of people with with a certain value in a specific attribute
df = entities_with_attribute(
    entity_type='person',
    show_elements=['name','groupname'],
    the_type='jesuita-entrada',
    the_value='Coimbra',
    more_attributes=['nascimento','estadia','estadia.obs','morte','morte.obs'],
    db=tlnb.db,
)
ids = list(df.index.unique())
print(len(ids),ids)
df

AttributeError: entity

In [ ]:

group = group_attributes(group=ids,
                         entity_type='person',
                         show_elements=['groupname','name'],
                         db=tlnb.db)
group.info()

In [8]:
group.head(10)

,groupname,name,the_type,the_value,the_date,attr_obs
id,,,,,,
deh-afonso-aires,n,Afonso Aires,nacionalidade,Portugal,0,
deh-afonso-aires,n,Afonso Aires,jesuita-estatuto,Padre,0,
deh-afonso-aires,n,Afonso Aires,nome,Afonso Ayres,0,
deh-afonso-aires,n,Afonso Aires,embarque,Bom Jesus da Vidigueira,16570404,
deh-afonso-aires,n,Afonso Aires,wicky,1043,16570404,
deh-afonso-aires,n,Afonso Aires,wicky-viagem,89,16570404,
deh-afonso-aires,n,Afonso Aires,morte,"[No mar, depois do Cabo da Boa Esperança]",16570000,
deh-afonso-aires,n,Afonso Aires,jesuita-entrada@wikidata,https://www.wikidata.org/wiki/Q45412,16490000,"extra_info: {""value"": {""original"": ""Coimbra""}}"
deh-afonso-aires,n,Afonso Aires,jesuita-entrada,Coimbra,16490000,"extra_info: {""value"": {""comment"": ""@wikidata:Q..."
deh-afonso-aires,n,Afonso Aires,tarefa,Estuda Teologia,16490000,

In [6]:
# NBVAL_IGNORE_OUTPUT

from timelink.pandas.group_attributes import display_group_attributes

display_group_attributes(ids,
                         entity_type='person',
                         # show name,sex,obs
                         header_elements=['name'],
                         # define which attributes to display in the header
                         header_attributes=['nacionalidade','jesuita-entrada'],
                         include_attributes=['estadia','partida'],
                         sort_attributes=['the_date'],
                         db=tlnb.db)