> First time use: follow instructions in the README.md file in this directory.


**[PT]** Português

---

**[EN]** English

Usar esta base para criar um novo Bloco de Notas

---

Use this template for a new Notebook


# Título


[Sumário]

---

# Title

[summary]

---
## Setup

In [1]:
from timelink.api.database import TimelinkDatabase

# SQLite database version
# db_dir = '../database/sqlite/'
# db: TimelinkDatabase = TimelinkDatabase(db_name='timelink-demo.db', db_path=db_dir)

# PostgreSQL database version
db_name = 'timelink-demo'
db: TimelinkDatabase = TimelinkDatabase(db_name=db_name, db_type='postgres')

In [2]:
db.table_names()

['entities',
 'syspar',
 'syslog',
 'kleiofiles',
 'attributes',
 'relations',
 'acts',
 'sources',
 'persons',
 'goods',
 'objects',
 'classes',
 'class_attributes',
 'rgeoentities',
 'rpersons',
 'geoentities',
 'rentities',
 'robjects',
 'escrituras',
 'aforamentos']

In [3]:
from timelink.api.models import Source

with db.session() as session:
    sources = session.query(Source).all()
    for source in sources:
        print(source)

fonte$Devedores/0/type=inventario orfanologico/ref=None/loc=None/kleiofile="/kleio-home/reference_sources/varia/Devedores.cli""/replaces=None/obs="""
      escritos de dividas registados no inventario post mortem do patrimonio do meio conego antonio de campos branco de eiras, falecido em 1786
  """
fonte$auc-alunos-264605-A-140337-140771/0/type=UC-AUC-ficheiro-alunos/ref=None/loc=Arquivo da Universidade de Coimbra/kleiofile="/kleio-home/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli""/replaces=None/obs="""
      """
             Âmbito e conteúdo

             O índice de alunos da Universidade de Coimbra, também conhecido, apenas, como ficheiro de alunos, foi elaborado entre 1940 e 1950, pelos funcionários do Arquivo, por decisão do doutor Mário Brandão, então diretor do Arquivo da Universidade, como o atestam os relatórios de atividades enviados anualmente ao reitor da Universidade (v. Correspondência expedida do Arquivo (SR), cx.2 (1942-1947) e cx. 3 (1948-1951) – cota AUC-IV-2.ªE-10-2-18 e 19).
             Os citados relatórios revelam, por exemplo, que em 1941-1942 foram elaboradas fichas relativas aos livros de matrículas de 1720 a 1756, num total de 23.400 verbetes, em 1942-1943 foram elaboradas fichas dos livros de 1685 a 1719 num total de 25.000 verbetes, etc.
             Engloba dados relativos aos alunos que frequentaram a Universidade, com menção da sua naturalidade e filiação (apenas o nome do pai). No caso de alunos de ordens religiosas apenas apresentam a indicação da ordem religiosa a que pertenciam (por vezes, de forma generalizada, como, por exemplo “religioso de Santa cruz, religioso de S. Bento”) uma vez que os dados de naturalidade e de filiação destes alunos não ficaram registados nos livros originais de matrículas ou de livros de atos e graus e provas de curso.
             Inclui as datas de matrícula na Universidade, desde 1537, na cadeira de Instituta (a partir de 1772, deixa de existir esta cadeira) e nas diversas faculdades: Teologia, Cânones, Leis, Medicina; em 1772 foram criadas a Faculdade de Matemática e a Faculdade de Filosofia e a partir de 1834 a Faculdade de Cânones e a Faculdade de Leis fundiram-se, dando origem à Faculdade de Direito. Inclui também datas de provas de curso e datas de exames e graus.
             Estes dados foram recolhidos na série documental de livros de matrículas que existem entre 1573 e 1908. Para os anos anteriores, os dados foram recolhidos em livros que incluem registos de diversos atos, nomeadamente: matrículas, atos e graus e de provas de curso, entre 1537 e 1572. Registe-se que figuram no índice apenas dois alunos anteriores a 1537: Luís Aires e Rodrigo de Gaia que frequentaram a Universidade desde 1536. Depois de 1908 figuram alguns alunos, nomeadamente o aluno Domingos Luiselo Alves Moreira (1915-1919) pois os seus dados foram incluídos posteriormente à elaboração do ficheiro original.
             Compreende os referidos dados redigidos em fichas individuais manuscritas, em trabalho cuja coordenação poderá ser atribuída ao Dr. António Gomes da Rocha Madahil, conservador do Arquivo e cuja elaboração pode ser atribuída aos funcionários que trabalharam no Arquivo, entre 1940 e 1950: António da Costa Rodrigues, Diamantino Ramos, António dos Santos Bernardino, Guilherme Flóreo dos Santos Bernardino, Francisco Ferrer Mendes da Silva.
             O último livro em que foram colhidos dados para o Índice de alunos é o volume 129 da série de Livros de Matrículas (cota: AUC-IV-1ªD-2-5-68).
             Este volume reporta-se ao ano lectivo de 1906-1907, com matrículas para as Faculdades de Teologia, Direito, Medicina, Matemática e Filosofia. No entanto, apesar de se destinar a este ano lectivo de 1906-1907 foram acrescentados alguns registos até 1911.

             Sistema de organização

             O índice foi elaborado em fichas individuais, apresentando em primeiro lugar o nome completo do aluno, tendo sido ordenado alfabeticamente pelo último apelido ou pelo nome dos dois últimos apelidos, no caso de nomes espanhóis ou de nomes compostos (ex. Castelo Branco, Lopes Júnior, etc.).
             Existem algumas fichas que são apenas remissivas para a forma completa do nome do aluno.
             Os dados do índice foram lançados na plataforma informática Archeevo, numa adaptação desta às necessidades imediatas de divulgação da informação, de forma a permitir um acesso mais rápido aos livros de matrículas e aos livros de atos e graus e provas de curso. Foi feita a atualização ortográfica dos nomes, como por exemplo Souza - Sousa, Paes - Pais, etc., bem como a atualização toponímica como, por exemplo, nos seguintes casos Punhete - Constância, Lavarrabos - São João do Campo, Farinha Podre - São Pedro de Alva.
             Ao fazer o registo informático, das fichas do índice, tornou-se necessário, para agilizar a pesquisa, reunir cada grupo de fichas com a mesma letra inicial dos apelidos como se se tratasse de uma unidade de instalação, desta forma o número de unidades de instalação corresponde ao das letras do alfabeto. Por outro lado, dentro de cada unidade de instalação (ou seja cada letra do alfabeto) ficou registada cada ficha como um documento simples.
             NOTA: Reconhece-se a existência de algumas lacunas na elaboração deste índice, no entanto, este é tornado público para facilitar a pesquisa dos investigadores.
             As correcções serão feitas pontualmente.

             URL: http://pesquisa.auc.uc.pt/details?id=264605
         """
  """
fonte$bapteirasproblem1/0/type=1787-1792/ref=None/loc=Auc/kleiofile="/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem1.cli""/replaces=None/obs=o livro inicia-se em 1784
fonte$auc_cartulario18/0/type=escrituras/ref=None/loc=auc/kleiofile="/kleio-home/reference_sources/varia/auc_cartulario18.cli""/replaces=None/obs=livro encadernado de notas n�18, santa clara de coimbra, cota:iii-1.d-16-3-19, tabeliao gregorio lourenco
fonte$lousa-bapt1714/0/type=bapt/ref=None/loc=None/kleiofile="/kleio-home/reference_sources/paroquiais/baptismos/bapt1714.cli""/replaces=None/obs=freguesia de sao silvestre da lousalousa
fonte$bapteirasproblem2/0/type=1752-1753/ref=None/loc=Auc/kleiofile="/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli""/replaces=None/obs= o livro inicia-se em 1623

### Setup Kleio server

In [4]:
from timelink.kleio import KleioServer

kleio_home_found = KleioServer.find_local_kleio_home()
print(f"Kleio Home Found: {kleio_home_found}")

kserver: KleioServer = KleioServer.start(kleio_home=kleio_home_found)
token = kserver.get_token()
url = kserver.get_url()
khome = kserver.get_kleio_home()

print(f"Token: {token[:4]}")
print(f"URL: {url}")
print(f"Kleio Home: {khome}")

Kleio Home Found: /Users/jrc/develop/timelink-py/tests/timelink-home/sources/test-project
Token: Fp9Y
URL: http://127.0.0.1:8089
Kleio Home: /Users/jrc/develop/timelink-py/tests/timelink-home/sources/test-project


# importar dados
---

# Import data

Translate new and updated files

In [5]:
for kfile in kserver.translation_status(path='',recurse='yes',status='T'):
    print(kfile.status.value, kfile.path)
    kserver.translate(kfile.path, recurse='no', spawn='no')

Check which files where translated sucessfully

```

In [6]:
ready_to_import = kserver.translation_status(path='',recurse='yes',status='V')
for ready in ready_to_import:
    print(ready.status.value, ready.path)
ready_to_import

V kleio/reference_sources/varia/Devedores.cli
V kleio/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli
V kleio/reference_sources/varia/auc_cartulario18.cli
V kleio/reference_sources/paroquiais/baptismos/bapt1714.cli
V kleio/reference_sources/paroquiais/baptismos/bapteirasproblem1.cli
V kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli
V kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.cli
V kleio/reference_sources/paroquiais/casamentos/cas1714-1722.cli
V kleio/reference_sources/roisdeconfessados/coja-rol-1841.cli
V kleio/reference_sources/paroquiais/crisma/crisma1753.cli
V kleio/reference_sources/linked_data/dehergne-a.cli
V kleio/reference_sources/linked_data/dehergne-locations-1644.cli
V kleio/reference_sources/notariais/docsregiospontepisc.cli
V kleio/reference_sources/roisdeconfessados/eiras-rol1.cli
V kleio/reference_sources/roisdeconfessados/eiras-rol2.cli
V kleio/reference_sources/roisdeconfessados/eiras-rol3.cli
V kleio/reference_sources/varia/eleicoes1.cli
V kleio/reference_sources/varia/genealdiversas.cli
V kleio/reference_sources/varia/ivcc.cli
V kleio/reference_sources/varia/lrazao516pe.cli
V kleio/reference_sources/varia/misMesa.cli
V kleio/reference_sources/varia/mp758-santiago-beduido.cli
V kleio/reference_sources/notariais/notlousa1.cli
V kleio/reference_sources/paroquiais/obitos/obit1714.cli
V kleio/reference_sources/paroquiais/obitos/obitoShort.cli
V kleio/reference_sources/paroquiais/obitos/obitoShort_id.cli
V kleio/reference_sources/notariais/perdoes.cli
V kleio/reference_sources/varia/quotes.cli
V kleio/reference_sources/paroquiais/baptismos/rogeriodomingos_bap_problem.cli
V kleio/reference_sources/varia/sourecoimbrabispcoimbra_apontamentosd.cli
V kleio/reference_sources/paroquiais/obitos/testeParentescos.cli
V kleio/reference_sources/varia/vereacao.cli
V kleio/reference_sources/varia/xpto_comuns_soure.kleio

[KleioFile(path='kleio/reference_sources/varia/Devedores.cli', name='Devedores.cli', size=3249, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 40, 24, 558032, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 24, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:24', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/Devedores.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/Devedores.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/Devedores.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli', name='auc-alunos-264605-A-140337-140771.cli', size=1381330, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 41, 36, 182369, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 36, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:36', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/auc-alunos-264605-A-140337-140771.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/auc-alunos-264605-A-140337-140771.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/varia/auc_cartulario18.cli', name='auc_cartulario18.cli', size=101268, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 40, 30, 846396, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 30, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:30', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/auc_cartulario18.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/auc_cartulario18.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/auc_cartulario18.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/paroquiais/baptismos/bapt1714.cli', name='bapt1714.cli', size=43942, directory='kleio/reference_sources/paroquiais/baptismos', modified=datetime.datetime(2023, 11, 30, 8, 40, 29, 725083, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 29, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:29', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/paroquiais/baptismos/bapt1714.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/paroquiais/baptismos/bapt1714.rpt', xml_url='/rest/exports/kleio/reference_sources/paroquiais/baptismos/bapt1714.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/paroquiais/baptismos/bapteirasproblem1.cli', name='bapteirasproblem1.cli', size=97925, directory='kleio/reference_sources/paroquiais/baptismos', modified=datetime.datetime(2023, 11, 30, 8, 40, 35, 781222, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 35, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:35', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/paroquiais/baptismos/bapteirasproblem1.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/paroquiais/baptismos/bapteirasproblem1.rpt', xml_url='/rest/exports/kleio/reference_sources/paroquiais/baptismos/bapteirasproblem1.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', name='bapteirasproblem2.cli', size=136532, directory='kleio/reference_sources/paroquiais/baptismos', modified=datetime.datetime(2023, 11, 30, 8, 40, 39, 477015, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 39, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:39', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.rpt', xml_url='/rest/exports/kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.cli', name='cas1714-1722-com-celebrante.cli', size=2034, directory='kleio/reference_sources/paroquiais/casamentos', modified=datetime.datetime(2023, 11, 30, 8, 40, 36, 636962, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 36, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:36', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.rpt', xml_url='/rest/exports/kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/paroquiais/casamentos/cas1714-1722.cli', name='cas1714-1722.cli', size=94359, directory='kleio/reference_sources/paroquiais/casamentos', modified=datetime.datetime(2023, 11, 30, 8, 40, 42, 834655, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 42, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:42', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/paroquiais/casamentos/cas1714-1722.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/paroquiais/casamentos/cas1714-1722.rpt', xml_url='/rest/exports/kleio/reference_sources/paroquiais/casamentos/cas1714-1722.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/roisdeconfessados/coja-rol-1841.cli', name='coja-rol-1841.cli', size=213581, directory='kleio/reference_sources/roisdeconfessados', modified=datetime.datetime(2023, 11, 30, 8, 41, 2, 348866, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 2, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:02', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/roisdeconfessados/coja-rol-1841.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/roisdeconfessados/coja-rol-1841.rpt', xml_url='/rest/exports/kleio/reference_sources/roisdeconfessados/coja-rol-1841.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/paroquiais/crisma/crisma1753.cli', name='crisma1753.cli', size=1590, directory='kleio/reference_sources/paroquiais/crisma', modified=datetime.datetime(2023, 11, 30, 8, 40, 43, 680802, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 43, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:43', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/paroquiais/crisma/crisma1753.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/paroquiais/crisma/crisma1753.rpt', xml_url='/rest/exports/kleio/reference_sources/paroquiais/crisma/crisma1753.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/linked_data/dehergne-a.cli', name='dehergne-a.cli', size=119167, directory='kleio/reference_sources/linked_data', modified=datetime.datetime(2023, 11, 30, 8, 40, 48, 32186, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 48, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:48', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/linked_data/dehergne-a.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/linked_data/dehergne-a.rpt', xml_url='/rest/exports/kleio/reference_sources/linked_data/dehergne-a.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/linked_data/dehergne-locations-1644.cli', name='dehergne-locations-1644.cli', size=48349, directory='kleio/reference_sources/linked_data', modified=datetime.datetime(2023, 11, 30, 8, 40, 50, 72934, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 50, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:50', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/linked_data/dehergne-locations-1644.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/linked_data/dehergne-locations-1644.rpt', xml_url='/rest/exports/kleio/reference_sources/linked_data/dehergne-locations-1644.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/notariais/docsregiospontepisc.cli', name='docsregiospontepisc.cli', size=2175, directory='kleio/reference_sources/notariais', modified=datetime.datetime(2023, 11, 30, 8, 40, 50, 898425, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 50, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:50', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/notariais/docsregiospontepisc.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/notariais/docsregiospontepisc.rpt', xml_url='/rest/exports/kleio/reference_sources/notariais/docsregiospontepisc.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/roisdeconfessados/eiras-rol1.cli', name='eiras-rol1.cli', size=52584, directory='kleio/reference_sources/roisdeconfessados', modified=datetime.datetime(2023, 11, 30, 8, 40, 55, 89939, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 55, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:55', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/roisdeconfessados/eiras-rol1.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/roisdeconfessados/eiras-rol1.rpt', xml_url='/rest/exports/kleio/reference_sources/roisdeconfessados/eiras-rol1.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/roisdeconfessados/eiras-rol2.cli', name='eiras-rol2.cli', size=51851, directory='kleio/reference_sources/roisdeconfessados', modified=datetime.datetime(2023, 11, 30, 8, 40, 59, 229912, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 40, 59, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:40:59', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/roisdeconfessados/eiras-rol2.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 40, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:40:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/roisdeconfessados/eiras-rol2.rpt', xml_url='/rest/exports/kleio/reference_sources/roisdeconfessados/eiras-rol2.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/roisdeconfessados/eiras-rol3.cli', name='eiras-rol3.cli', size=52776, directory='kleio/reference_sources/roisdeconfessados', modified=datetime.datetime(2023, 11, 30, 8, 41, 3, 466071, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 3, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:03', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/roisdeconfessados/eiras-rol3.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/roisdeconfessados/eiras-rol3.rpt', xml_url='/rest/exports/kleio/reference_sources/roisdeconfessados/eiras-rol3.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/varia/eleicoes1.cli', name='eleicoes1.cli', size=50693, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 41, 6, 107869, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 6, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:06', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/eleicoes1.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/eleicoes1.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/eleicoes1.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/varia/genealdiversas.cli', name='genealdiversas.cli', size=71568, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 41, 7, 240938, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 7, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:07', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/genealdiversas.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/genealdiversas.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/genealdiversas.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/varia/ivcc.cli', name='ivcc.cli', size=48446, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 41, 9, 254068, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 9, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:09', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/ivcc.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/ivcc.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/ivcc.xml', import_status=None),
 KleioFile(path='kleio/reference_sources/varia/lrazao516pe.cli', name='lrazao516pe.cli', size=165942, directory='kleio/reference_sources/varia', modified=datetime.datetime(2023, 11, 30, 8, 41, 20, 753355, tzinfo=TzInfo(UTC)), modified_iso=datetime.datetime(2023, 11, 30, 8, 41, 20, tzinfo=TzInfo(UTC)), modified_string='2023-11-30 08:41:20', qtime=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=TzInfo(UTC)), qtime_string='1970-01-01 00:00:00', source_url='/rest/sources/kleio/reference_sources/varia/lrazao516pe.cli', status=<translation_status_enum.V: 'V'>, translated=datetime.datetime(2023, 11, 30, 8, 41, tzinfo=TzInfo(UTC)), translated_string='2023-11-30T08:41:00+00:00', errors=0, warnings=0, version='KleioTranslator - server version 12.0 - build 553 2023-09-27 16:03:59', rpt_url='/rest/reports/kleio/reference_sources/varia/lrazao516pe.rpt', xml_url='/rest/exports/kleio/reference_sources/varia/lrazao516pe.xml', import_status=None),

Check if the import status of the translated files

    I = "I" # imported
    E = "E" # imported with error
    W = "W" # imported with warnings no errors
    N = "N" # not imported
    U = "U" # translation updated need to reimport

In [7]:

need_import = db.get_import_status(ready_to_import, match_path=False)
for kfile in need_import:
    if kfile.import_status is None:
        istatus = "None"
    else:
        istatus = kfile.import_status.value
    print(istatus, kfile.path)
    # db.import_kleio_file(kfile.path, khome=khome)

I kleio/reference_sources/varia/Devedores.cli
I kleio/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli
E kleio/reference_sources/varia/auc_cartulario18.cli
E kleio/reference_sources/paroquiais/baptismos/bapt1714.cli
I kleio/reference_sources/paroquiais/baptismos/bapteirasproblem1.cli
N kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli
N kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.cli
N kleio/reference_sources/paroquiais/casamentos/cas1714-1722.cli
N kleio/reference_sources/roisdeconfessados/coja-rol-1841.cli
N kleio/reference_sources/paroquiais/crisma/crisma1753.cli
N kleio/reference_sources/linked_data/dehergne-a.cli
N kleio/reference_sources/linked_data/dehergne-locations-1644.cli
N kleio/reference_sources/notariais/docsregiospontepisc.cli
N kleio/reference_sources/roisdeconfessados/eiras-rol1.cli
N kleio/reference_sources/roisdeconfessados/eiras-rol2.cli
N kleio/reference_sources/roisdeconfessados/eiras-rol3.cli
N kleio/reference_sources/varia/eleicoes1.cli
N kleio/reference_sources/varia/genealdiversas.cli
N kleio/reference_sources/varia/ivcc.cli
N kleio/reference_sources/varia/lrazao516pe.cli
N kleio/reference_sources/varia/misMesa.cli
N kleio/reference_sources/varia/mp758-santiago-beduido.cli
N kleio/reference_sources/notariais/notlousa1.cli
N kleio/reference_sources/paroquiais/obitos/obit1714.cli
N kleio/reference_sources/paroquiais/obitos/obitoShort.cli
N kleio/reference_sources/paroquiais/obitos/obitoShort_id.cli
N kleio/reference_sources/notariais/perdoes.cli
N kleio/reference_sources/varia/quotes.cli
N kleio/reference_sources/paroquiais/baptismos/rogeriodomingos_bap_problem.cli
N kleio/reference_sources/varia/sourecoimbrabispcoimbra_apontamentosd.cli
N kleio/reference_sources/paroquiais/obitos/testeParentescos.cli
N kleio/reference_sources/varia/vereacao.cli
N kleio/reference_sources/varia/xpto_comuns_soure.kleio

Import from Kleio Server

In [11]:
import pprint
from timelink.kleio.schemas import KleioFile
from timelink.kleio.importer import import_from_xml
from datetime import datetime

valid = kserver.translation_status(path='',recurse='yes',status='V')
warnings = kserver.translation_status(path='',recurse='yes',status='W')
to_import = db.get_need_import(valid+warnings, match_path=False)

kfile: KleioFile

with db.session() as session:
    for kfile in to_import:
        print()
        print(kfile.status.value, kfile.path)
        try:
            stats = import_from_xml(kfile.xml_url, session=session,
                                    options={"return_stats": True,
                                             "kleio_token": token,
                                             "kleio_url": url,
                                             "mode":"TL"})
            formatted_date = datetime.fromtimestamp(stats['datetime']).strftime('%Y-%m-%d %H:%M:%S')
            print(f"E:{stats['nerrors']}", formatted_date, stats['file'])
            for error in stats['errors']:
                print(f"Error returned ->  {error}")
        except Exception as e:
            print()
            print("Unexpected error:")
            print(f"Error: {e}")
            continue

V kleio/reference_sources/varia/auc_cartulario18.cli
Storing 7 postponed relations
E:2 2023-12-05 17:36:59 /rest/exports/kleio/reference_sources/varia/auc_cartulario18.xml
Error ->  ERROR: auc_cartulario18.cli 228 storing rel$class=relation/date=15230508/groupname=rel/id=esc1523-e7-per3-rel1-3/destination=esc1520-e7-per2/level=4/line=228/undef=afonso dias/order=218/type=parentesco/value=mulher
 (psycopg2.errors.ForeignKeyViolation) insert or update on table "relations" violates foreign key constraint "relations_destination_fkey"
DETAIL:  Key (destination)=(esc1520-e7-per2) is not present in table "entities".

[SQL: INSERT INTO relations (id, origin, destination, the_type, the_value, the_date, obs) VALUES (%(id)s, %(origin)s, %(destination)s, %(the_type)s, %(the_value)s, %(the_date)s, %(obs)s)]
[parameters: {'id': 'esc1523-e7-per3-rel1-3', 'origin': 'esc1523-e7-per3', 'destination': 'esc1520-e7-per2', 'the_type': 'parentesco', 'the_value': 'mulher', 'the_date': '15230508', 'obs': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Error ->  ERROR: auc_cartulario18.cli 1039 storing rel$class=relation/date=15380525/groupname=rel/id=esc1538-e31-per3-rel1-3/destination=sc1538-e31-per2/level=4/line=1039/undef=lopo eanes/order=1005/type=parentesco/value=mulher
 (psycopg2.errors.ForeignKeyViolation) insert or update on table "relations" violates foreign key constraint "relations_destination_fkey"
DETAIL:  Key (destination)=(sc1538-e31-per2) is not present in table "entities".

[SQL: INSERT INTO relations (id, origin, destination, the_type, the_value, the_date, obs) VALUES (%(id)s, %(origin)s, %(destination)s, %(the_type)s, %(the_value)s, %(the_date)s, %(obs)s)]
[parameters: {'id': 'esc1538-e31-per3-rel1-3', 'origin': 'esc1538-e31-per3', 'destination': 'sc1538-e31-per2', 'the_type': 'parentesco', 'the_value': 'mulher', 'the_date': '15380525', 'obs': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

V kleio/reference_sources/paroquiais/baptismos/bapt1714.cli
Storing 1 postponed relations
E:1 2023-12-05 17:37:20 /rest/exports/kleio/reference_sources/paroquiais/baptismos/bapt1714.xml
Error ->  ERROR: bapt1714.cli 553 storing rel$class=relation/date=17140421/groupname=rel/id=lousa-b1714-25-per5-rel1-2/destination=lousa-b1714-p3/level=5/line=553/undef=luzia de sao jose/order=637/type=sociailidade/value=procurador
 (psycopg2.errors.ForeignKeyViolation) insert or update on table "relations" violates foreign key constraint "relations_destination_fkey"
DETAIL:  Key (destination)=(lousa-b1714-p3) is not present in table "entities".

[SQL: INSERT INTO relations (id, origin, destination, the_type, the_value, the_date, obs) VALUES (%(id)s, %(origin)s, %(destination)s, %(the_type)s, %(the_value)s, %(the_date)s, %(obs)s)]
[parameters: {'id': 'lousa-b1714-25-per5-rel1-2', 'origin': 'lousa-b1714-25-per5', 'destination': 'lousa-b1714-p3', 'the_type': 'sociailidade', 'the_value': 'procurador', 'the_date': '17140421', 'obs': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

V kleio/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli
Storing 18 postponed relations

Unexpected error:
Error: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

V kleio/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/paroquiais/casamentos/cas1714-1722.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/roisdeconfessados/coja-rol-1841.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/paroquiais/crisma/crisma1753.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/linked_data/dehergne-a.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/linked_data/dehergne-locations-1644.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/notariais/docsregiospontepisc.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/roisdeconfessados/eiras-rol1.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/roisdeconfessados/eiras-rol2.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)

[SQL: INSERT INTO kleiofiles (path, name, structure, translator, translation_date, nerrors, nwarnings, error_rpt, warning_rpt, imported, imported_string) VALUES (%(path)s, %(name)s, %(structure)s, %(translator)s, %(translation_date)s, %(nerrors)s, %(nwarnings)s, %(error_rpt)s, %(warning_rpt)s, %(imported)s, %(imported_string)s)]
[parameters: {'path': '/kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli', 'name': 'bapteirasproblem2.cli', 'structure': '/usr/local/timelink/clio/src/gacto2.str', 'translator': 'gactoxml2.str', 'translation_date': datetime.datetime(2023, 11, 30, 8, 40, 31), 'nerrors': 16, 'nwarnings': 0, 'error_rpt': 'ERROR: bapteirasproblem2.cli 266 storing rel$class=relation/date=17590318/groupname=rel/id=b1759.518-per8-rel1-2/destination=1759-b515-antonio/level= ... (14401 characters truncated) ... entification\', \'the_value\': \'same as\', \'the_date\': \'17630417\', \'obs\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)', 'warning_rpt': 'No warnings', 'imported': datetime.datetime(2023, 12, 5, 9, 38, 34, 170248, tzinfo=datetime.timezone.utc), 'imported_string': '2023-12-05 09:38:34 UTC'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h) (Background on this error at: https://sqlalche.me/e/20/7s2a)

V kleio/reference_sources/roisdeconfessados/eiras-rol3.cli

Unexpected error:
Error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10000)


Import status after import

In [15]:
from typing import List
from timelink.api.models.system import KleioImportedFile

imported_files: List[KleioImportedFile] = db.get_imported_files()
ifile: KleioImportedFile

for ifile in imported_files:
    print(ifile.nerrors, ifile.nwarnings, ifile.path)

0 0 /kleio-home/reference_sources/varia/Devedores.cli
0 0 /kleio-home/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli
0 0 /kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem1.cli
1 0 /kleio-home/reference_sources/paroquiais/baptismos/bapt1714.cli
2 0 /kleio-home/reference_sources/varia/auc_cartulario18.cli
16 0 /kleio-home/reference_sources/paroquiais/baptismos/bapteirasproblem2.cli
0 0 /kleio-home/reference_sources/paroquiais/casamentos/cas1714-1722-com-celebrante.cli
0 0 /kleio-home/reference_sources/paroquiais/casamentos/cas1714-1722.cli
0 0 /kleio-home/reference_sources/roisdeconfessados/coja-rol-1841.cli
1 0 /kleio-home/reference_sources/paroquiais/crisma/crisma1753.cli
4 0 /kleio-home/reference_sources/linked_data/dehergne-a.cli
0 0 /kleio-home/reference_sources/linked_data/dehergne-locations-1644.cli
0 0 /kleio-home/reference_sources/notariais/docsregiospontepisc.cli
0 0 /kleio-home/reference_sources/varia/eleicoes1.cli
9 0 /kleio-home/reference_sources/roisdeconfessados/eiras-rol1.cli
3 0 /kleio-home/reference_sources/roisdeconfessados/eiras-rol2.cli
3 0 /kleio-home/reference_sources/roisdeconfessados/eiras-rol3.cli
8 0 /kleio-home/reference_sources/varia/genealdiversas.cli
16 0 /kleio-home/reference_sources/varia/ivcc.cli


# Obter dados
---

# Getting data



###  Obter um dataframe a partir de atributos

---


###  Get a Dataframe from attributes

In [34]:
from timelink.api.models import Person

with db.session() as session:
    persons = session.query(Person).filter_by(name='maria').all()
    for person in persons:
        print(person.to_kleio())
        print()

n$maria/f/id=b1685.1-per1
  rel$function-in-act/n/b1685.1/16850708
  pai$manuel madeira/m/id=b1685.1-per1-per2
    rel$function-in-act/pai/b1685.1/16850708
    ls$residencia/alencarce/16850708
  mae$domingas joao/f/id=b1685.1-per1-per3
    rel$function-in-act/mae/b1685.1/16850708
  pad$antonio jorge/m/id=b1685.1-per4
    rel$function-in-act/pad/b1685.1/16850708
    ls$residencia/alencarce/16850708
  mad$maria/f/id=b1685.1-per5
    rel$function-in-act/mad/b1685.1/16850708
    ls$ec/s/16850708
    ls$residencia/alencarce/16850708

mad$maria/f/id=b1685.1-per5
  rel$function-in-act/mad/b1685.1/16850708
  ls$ec/s/16850708
  ls$residencia/alencarce/16850708

n$maria/f/id=b1685.2-per1
  rel$function-in-act/n/b1685.2/16850728
  pai$matias rodrigues/m/id=b1685.2-per1-per2
    rel$function-in-act/pai/b1685.2/16850728
    ls$residencia/casa velha/16850728
  mae$maria donana?/f/id=b1685.2-per1-per3
    rel$function-in-act/mae/b1685.2/16850728
  pad$antonio da fonseca/m/id=b1685.2-per4
    rel$function-in-act/pad/b1685.2/16850728
    ls$residencia/cumieira, freguesia de Penela/16850728
    ls$freguesia/penela/16850728
  mad$maria pereira/f/id=b1685.2-per5
    rel$function-in-act/mad/b1685.2/16850728
    pmad$manuel simoes/m/id=b1685.2-per6
      rel$function-in-act/pmad/b1685.2/16850728
      ls$residencia/casa velha/16850728

mad$maria/f/id=b1685.6-per5
  rel$function-in-act/mad/b1685.6/16850827
  ls$ec/s/16850827
  pmad$calvo/m/id=b1685.6-per6
    rel$function-in-act/pmad/b1685.6/16850827
    ls$residencia/casa velha/16850827

n$maria/f/id=b1685.10-per1
  rel$function-in-act/n/b1685.10/16850912
  pai$matias de carvalho/m/id=b1685.10-per1-per2
    rel$function-in-act/pai/b1685.10/16850912
    ls$residencia/soure/16850912
  mae$ana velho/f/id=b1685.10-per1-per3
    rel$function-in-act/mae/b1685.10/16850912
  pad$pedro de brito de ataide/m/id=b1685.10-per4
    rel$function-in-act/pad/b1685.10/16850912
    ls$residencia/quinta da capa rota/16850912

n$maria/f/id=b1685.12-per1
  rel$function-in-act/n/b1685.12/16850923
  pai$manuel rodrigues claro/m/id=b1685.12-per1-per2
    rel$function-in-act/pai/b1685.12/16850923
    ls$residencia/alencarce/16850923
    ls$morto/antes/16850923
  mae$maria alves/f/id=b1685.12-per1-per3
    rel$function-in-act/mae/b1685.12/16850923
    ls$ec/v/16850923
    ls$residencia/alencarce/16850923

n$maria/f/id=b1685.16-per1
  rel$function-in-act/n/b1685.16/16851014
  pai$manuel jorge/m/id=b1685.16-per1-per2
    rel$function-in-act/pai/b1685.16/16851014
    ls$residencia/sobral/16851014
  mae$maria cordeiro/f/id=b1685.16-per1-per3
    rel$function-in-act/mae/b1685.16/16851014
  pad$manuel simoes/m/id=b1685.16-per4
    rel$function-in-act/pad/b1685.16/16851014
    ls$residencia/sobral/16851014
  mad$maria cordeiro/f/id=b1685.16-per5
    rel$function-in-act/mad/b1685.16/16851014
    ls$residencia/sobral/16851014

n$maria/f/id=b1685.21-per1
  rel$function-in-act/n/b1685.21/16851104
  pai$manuel de oliveira/m/id=b1685.21-per1-per2
    rel$function-in-act/pai/b1685.21/16851104
    ls$residencia/lajem/16851104
  mae$maria lopes/f/id=b1685.21-per1-per3
    rel$function-in-act/mae/b1685.21/16851104
  pad$manuel rodrigues/m/id=b1685.21-per4
    rel$function-in-act/pad/b1685.21/16851104
  mad$ines ?/f/id=b1685.21-per5
    rel$function-in-act/mad/b1685.21/16851104
    mrmad$manuel de tavora/m/id=b1685.21-per6
      rel$function-in-act/mrmad/b1685.21/16851104
      ls$residencia/soure/16851104

n$maria/f/id=b1685.25-per1
  rel$function-in-act/n/b1685.25/16851118
  pai$joao rodrigues/m/id=b1685.25-per1-per2
    rel$function-in-act/pai/b1685.25/16851118
    ls$residencia/alencarce de baixo/16851118
  mae$isabel cardoso/f/id=b1685.25-per1-per3
    rel$function-in-act/mae/b1685.25/16851118
  pad$manuel goncalves/m/id=b1685.25.4
    rel$function-in-act/pad/b1685.25/16851118
    ls$residencia/alencarce/16851118
  mad$maria/f/id=b1685.25-per4
    rel$function-in-act/mad/b1685.25/16851118
    rel$parentesco/filha/manuel goncalves/b1685.25.4/16851118

mad$maria/f/id=b1685.25-per4
  rel$function-in-act/mad/b1685.25/16851118
  rel$parentesco/filha/manuel goncalves/b1685.25.4/16851118

n$maria/f/id=b1685.27b.1
  rel$function-in-act/n/b1685.27b/16851125
  pai$manuel francisco/m/id=b1685.27b.1-per1
    rel$function-in-act/pai/b1685.27b/16851125
    ls$residencia/casal das galinhas/16851125
  mae$ana jorge/f/id=b1685.27b.1-per2
    rel$function-in-act/mae/b1685.27b/16851125
  pad$joao da costa de vasconcelos/m/id=b1685.27b-per3
    rel$function-in-act/pad/b1685.27b/16851125
  mad$helena/f/id=b1685.27b-per4
    rel$function-in-act/mad/b1685.27b/16851125
    ls$titulo/dona/16851125
    pmad$paulo ribeiro cabral/m/id=b1685.27b-per5
      rel$function-in-act/pmad/b1685.27b/16851125

mad$maria/f/id=b1685.33-per5
  rel$function-in-act/mad/b1685.33/16851226
  ls$ec/s/16851226
  pmad$domingos goncalves vargas/m/id=b1685.33-per6
    rel$function-in-act/pmad/b1685.33/16851226
    ls$residencia/casal de vale da borra/16851226

In [3]:
from timelinknb.pandas import attribute_to_df


# Get list of people with with a certain value in a specific attribute
df = attribute_to_df(
                    the_type='naturalidade',
                    the_value='Coimbra',
                    person_info=True,
                    more_cols=['faculdade','uc-entrada','uc-saida','grau'],
                    sql_echo=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8543 entries, 127765 to 355146
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               8543 non-null   object
 1   sex                8543 non-null   object
 2   naturalidade       8543 non-null   object
 3   naturalidade.date  8543 non-null   object
 4   naturalidade.obs   2 non-null      object
 5   faculdade          8282 non-null   object
 6   faculdade.date     8282 non-null   object
 7   faculdade.obs      8282 non-null   object
 8   uc-entrada         8543 non-null   object
 9   uc-entrada.date    8543 non-null   object
 10  uc-entrada.obs     0 non-null      object
 11  uc-saida           8543 non-null   object
 12  uc-saida.date      8543 non-null   object
 13  uc-saida.obs       0 non-null      object
 14  grau               4901 non-null   object
 15  grau.date          4901 non-null   object
 16  grau.obs           4901 non-null   object
dtypes: object(17)
memory usage: 1.2+ MB

In [4]:
df.head(5)

,name,sex,naturalidade,naturalidade.date,naturalidade.obs,faculdade,faculdade.date,faculdade.obs,uc-entrada,uc-entrada.date,uc-entrada.obs,uc-saida,uc-saida.date,uc-saida.obs,grau,grau.date,grau.obs
id,,,,,,,,,,,,,,,,,
127765,André Vaz Cabaço,m,Coimbra,0000-00-00,None,NaN,NaN,NaN,0000-00-00,0000-00-00,None,0000-00-00,0000-00-00,None,NaN,NaN,NaN
127815,Aires Tavares Cabral,m,Coimbra,1847-10-19,None,Direito,1847-10-19,Direito,1847-10-19,1847-10-19,None,1850-06-08,1850-06-08,None,NaN,NaN,NaN
127822,André da Veiga Cabral,m,Coimbra,1663-01-02,None,Cânones,1663-01-02,Cânones,1663-01-02,1663-01-02,None,1665-10-29,1665-10-29,None,NaN,NaN,NaN
128131,Cassiano Tomás Cabral,m,Coimbra,1817-10-20,None,Filosofia,1817-10-20,Filosofia,1817-10-20,1817-10-20,None,1817-10-20,1817-10-20,None,NaN,NaN,NaN
128132,Cipriano Tavares Cabral,m,Coimbra,1817-10-18,None,Matemática,1817-10-18,Matemática,1817-10-18,1817-10-18,None,1817-10-18,1817-10-18,None,NaN,NaN,NaN



###  Remover colunas sem valores

---



###  Remove empty columns

In [5]:
df.dropna(how='all', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8543 entries, 127765 to 355146
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               8543 non-null   object
 1   sex                8543 non-null   object
 2   naturalidade       8543 non-null   object
 3   naturalidade.date  8543 non-null   object
 4   naturalidade.obs   2 non-null      object
 5   faculdade          8282 non-null   object
 6   faculdade.date     8282 non-null   object
 7   faculdade.obs      8282 non-null   object
 8   uc-entrada         8543 non-null   object
 9   uc-entrada.date    8543 non-null   object
 10  uc-saida           8543 non-null   object
 11  uc-saida.date      8543 non-null   object
 12  grau               4901 non-null   object
 13  grau.date          4901 non-null   object
 14  grau.obs           4901 non-null   object
dtypes: object(15)
memory usage: 1.0+ MB


###  Remover as remissivas
---

###  Remove cross-references

In [6]:
no_crossref = df['uc-entrada'] != '0000-00-00'
df = df[no_crossref]

In [7]:
view_cols = ['name','naturalidade','faculdade','grau','grau.date','uc-entrada','uc-saida']
df[view_cols].head(10)

,name,naturalidade,faculdade,grau,grau.date,uc-entrada,uc-saida
id,,,,,,,
127815,Aires Tavares Cabral,Coimbra,Direito,NaN,NaN,1847-10-19,1850-06-08
127822,André da Veiga Cabral,Coimbra,Cânones,NaN,NaN,1663-01-02,1665-10-29
128131,Cassiano Tomás Cabral,Coimbra,Filosofia,NaN,NaN,1817-10-20,1817-10-20
128132,Cipriano Tavares Cabral,Coimbra,Matemática,NaN,NaN,1817-10-18,1817-10-18
128133,Claúdio Tavares Cabral,Coimbra,Filosofia,NaN,NaN,1820-11-15,1820-11-15
128151,Estevão Nogueira Cabral,Coimbra,Leis,NaN,NaN,1580-03-20,1580-03-20
128265,António Dias Cabreira,Coimbra,Cânones,Bacharel em Leis,1650-07-01,1645-01-24,1660-10-14
128265,António Dias Cabreira,Coimbra,Cânones,Formatura em Cânones,1659-10-03,1645-01-24,1660-10-14
128265,António Dias Cabreira,Coimbra,Leis,Bacharel em Leis,1650-07-01,1645-01-24,1660-10-14
128265,António Dias Cabreira,Coimbra,Leis,Formatura em Cânones,1659-10-03,1645-01-24,1660-10-14


## Contagens

---

## Counting


###  Contagem de atributos a partir de uma tabela em memória
 
---

###  Count attributes from an existing dataframe

In [8]:
# create a column with the index values which are the id numbers
df['id'] = df.index.values

col = 'faculdade' # subotal by this column

# Use pandas groupby and specify unique value count for id
df_totals = df.groupby(col).agg({'id':'nunique',
                                                  'uc-entrada':'min',
                                                  'uc-saida':'max'})

df_totals.sort_values('id',ascending= False).head(30)

                                      id  uc-entrada    uc-saida
faculdade
Cânones                             2577  1537-00-00  1835-07-20
Medicina                             826  1537-12-17  1909-10-04
Teologia                             534  1540-01-27  1906-10-09
Leis                                 532  1537-05-12  1835-06-14
Cursos jurídicos (Cânones ou Leis)   418  1537-00-00  1835-10-14
Direito                              295  1822-10-31  1919-10-08
Artes                                268  1537-00-00  1780-10-12
Matemática                           229  1593-02-05  1910-10-15
Filosofia                            144  1770-10-01  1910-10-15
(?)                                   17  1587-10-18  1756-10-01
(Coimbra)                              4  1569-11-20  1853-05-27
(Cânones)                              3  1825-10-24  1899-10-12
(.)                                    2  1658-10-01  1750-10-01
(Leis)                                 2  1835-06-20  1840-02-06
(Tentativa)                            1  1765-10-01  1771-07-31
(Telogia)                              1  1664-10-01  1676-11-09
(Medecina)                             1  1760-02-04  1771-07-30
(Fiosofia)                             1  1789-10-06  1801-10-30
(Filosogia)                            1  1779-11-06  1786-10-16
(Filosfia)                             1  1880-06-08  1882-10-13
código                                 1  1540-00-00  1540-00-00

 
### Contagens na base de dados

Quando o atributo tem muitos valores e não é necessário
ter todas as pessoas em memória: contagem feita na base de dados

---

### Counting directly in the database
When there are many values and it is not 
necessary to have all the people in memory:
count directly in the database.

In [9]:
from timelinknb.pandas import attribute_values

df_totals = attribute_values('grau')

In [10]:
df_totals.head(10)

                                                count     date_in    date_max
value
Bacharel em Cânones                             21744  0000-00-00  2204-00-00
Formatura em Cânones                            18823  0617-00-00  2761-05-25
Bacharel em Artes                                6343  0000-00-00  1977-03-15
Bacharel em Leis                                 5963  0412-00-00  7150-01-20
Formatura em Leis                                5066  0517-00-00  6178-00-00
Bacharel em Direito                              4848  1740-03-07  1972-06-06
Formatura em Direito                             4597  0707-00-00  2904-07-08
Licenciado em Artes                              2936  0000-00-00  1785-04-06
Formatura em Medicina                            2299  1554-05-31  1904-07-30
Bacharel em Cursos jurídicos (Cânones ou Leis)   2210  1579-06-09  3787-07-03

#### Filtrar por datas

Para evitar remissivas com data zero

---

#### Filter by dates 

Avoid cross-references with zero date

In [11]:
df_totals = attribute_values('grau',dates_between=('1535','1919'))

In [12]:
df_totals.head(10)

                                                count     date_in    date_max
value
Bacharel em Cânones                             21735  1537-06-26  1912-06-06
Formatura em Cânones                            18810  1564-11-02  1880-05-28
Bacharel em Artes                                6336  1540-00-00  1872-05-18
Bacharel em Leis                                 5959  1537-12-18  1892-07-30
Formatura em Leis                                5061  1566-12-12  1912-06-25
Bacharel em Direito                              4831  1740-03-07  1917-11-03
Formatura em Direito                             4591  1733-03-28  1915-07-04
Licenciado em Artes                              2932  1540-04-14  1785-04-06
Formatura em Medicina                            2299  1554-05-31  1904-07-30
Bacharel em Cursos jurídicos (Cânones ou Leis)   2209  1579-06-09  1915-11-25

## Visualizar registos

---

## View records

### Visualizar uma pessoa

---

### View a person

#### Atributos de uma pessoa numa tabela, uma linha por attributo

---

#### Person attributes in a dataframe, one line per attribute

In [13]:
import pandas as pd
from timelinknb.pandas import group_attributes as person_attributes

pd.set_option('display.max_rows',1000)

id = '316297'
pdf = person_attributes([id])  # note id in a list
pdf[['date','type','value','attr_obs']].sort_values(['date','type'])

,date,type,value,attr_obs
id,,,,
316297,1774-11-15,faculdade,Cânones,Faculdade corrigida
316297,1774-11-15,faculdade-original,Direito - Cânones,None
316297,1774-11-15,faculdade.ano,Cânones.1774,Faculdade corrigida
316297,1774-11-15,matricula-classe,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,1774-11-15,matricula-classe.ano,"Curso jurídico, 1º ano.1774","Vol. III, L. I, fl. 20v."
316297,1774-11-15,matricula-curso,Curso jurídico,"Vol. III, L. I, fl. 20v."
316297,1774-11-15,matricula-curso.ano,Curso jurídico.1774,"Vol. III, L. I, fl. 20v."
316297,1774-11-15,naturalidade,Porto,None
316297,1774-11-15,naturalidade.ano,Porto.1774,None
316297,1774-11-15,nome,João Pedro Ribeiro,None
316297,1774-11-15,nome-apelido,Pedro Ribeiro,None
316297,1774-11-15,nome-apelido,Ribeiro,None
316297,1774-11-15,nome-geografico,Porto,None
316297,1774-11-15,nome-geografico.ano,Porto.1774,None
316297,1774-11-15,nome-pai,Pedro do Rosário Ribeiro,None
316297,1774-11-15,nome-primeiro,João,None
316297,1774-11-15,uc-entrada,1774-11-15,None
316297,1774-11-15,uc-entrada.ano,1774,None
316297,1775-00-00,matricula-classe,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,1775-00-00,matricula-classe,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-classe.ano,"Curso jurídico, 2º ano.1775","Vol. IV, L. I, fl. 48"
316297,1775-00-00,matricula-classe.ano,"Matemática, 1º ano.1775","Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-classe.obrigado,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-classe.obrigado.ano,"Matemática, 1º ano.1775","Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-curso,Curso jurídico,"Vol. IV, L. I, fl. 48"
316297,1775-00-00,matricula-curso.ano,Curso jurídico.1775,"Vol. IV, L. I, fl. 48"
316297,1775-00-00,matricula-faculdade,Matemática,"Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-faculdade.ano,Matemática.1775,"Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-faculdade.obrigado,Matemática,"Vol. IV, L. 4, fl. 48"
316297,1775-00-00,matricula-faculdade.obrigado.ano,Matemática.1775,"Vol. IV, L. 4, fl. 48"
316297,1776-10-08,matricula-classe,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-classe.ano,"Matemática, 1º ano.1776","Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-classe.obrigado,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-classe.obrigado.ano,"Matemática, 1º ano.1776","Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-faculdade,Matemática,"Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-faculdade.ano,Matemática.1776,"Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-faculdade.obrigado,Matemática,"Vol. V, L. IV, fl. 12v."
316297,1776-10-08,matricula-faculdade.obrigado.ano,Matemática.1776,"Vol. V, L. IV, fl. 12v."
316297,1776-10-18,matricula-classe,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,1776-10-18,matricula-classe.ano,"Curso jurídico, 2º ano.1776","Vol. V, L. I, fl. 35v."
316297,1776-10-18,matricula-curso,Curso jurídico,"Vol. V, L. I, fl. 35v."
316297,1776-10-18,matricula-curso.ano,Curso jurídico.1776,"Vol. V, L. I, fl. 35v."
316297,1777-10-06,matricula-classe,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,1777-10-06,matricula-classe.ano,"Cânones, 3º ano.1777","Vol. VI, fl. 10"
316297,1777-10-06,matricula-faculdade,Cânones,"Vol. VI, fl. 10"
316297,1777-10-06,matricula-faculdade.ano,Cânones.1777,"Vol. VI, fl. 10"
316297,1777-10-16,matricula-classe,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,1777-10-16,matricula-classe.ano,"Filosofia, 1º ano.1777","Vol. VI, L. VI, fl. 13"
316297,1777-10-16,matricula-faculdade,Filosofia,"Vol. VI, L. VI, fl. 13"
316297,1777-10-16,matricula-faculdade.ano,Filosofia.1777,"Vol. VI, L. VI, fl. 13"
316297,1778-05-16,exame,Exames3.º,"Aprovado Nemine Discrepante, Atos n.º 1, fl. 211"
316297,1778-10-02,matricula-classe,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,1778-10-02,matricula-classe.ano,"Cânones, 4º ano.1778","Vol VII, L. 2, fl. 26"
316297,1778-10-02,matricula-faculdade,Cânones,"Vol VII, L. 2, fl. 26"
316297,1778-10-02,matricula-faculdade.ano,Cânones.1778,"Vol VII, L. 2, fl. 26"
316297,1779-10-21,exame,ExamesBacharel e grau,"Aprovado Nemine Discrepante, Atos n.º 1, fl. 2..."
316297,1779-10-21,grau,Bacharel em Cânones,Bacharel e grau 21.10.1779 Aprovado Nemine Dis...
316297,1779-10-21,grau.ano,Bacharel em Cânones.1779,Bacharel e grau 21.10.1779 Aprovado Nemine Dis...
316297,1779-11-03,matricula-classe,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,1779-11-03,matricula-classe.ano,"Cânones, 5º ano.1779","Vol. VII, L. 2, fl. 42"
316297,1779-11-03,matricula-faculdade,Cânones,"Vol. VII, L. 2, fl. 42"
316297,1779-11-03,matricula-faculdade.ano,Cânones.1779,"Vol. VII, L. 2, fl. 42"
316297,1780-11-27,matricula-classe,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,1780-11-27,matricula-classe.ano,"Cânones, 6º ano.1780","Vol IX, L. 3, fl. 73"
316297,1780-11-27,matricula-faculdade,Cânones,"Vol IX, L. 3, fl. 73"
316297,1780-11-27,matricula-faculdade.ano,Cânones.1780,"Vol IX, L. 3, fl. 73"
316297,1781-03-20,exame,ExamesRepetição,"Atos grandes n.º 1, fl. 5"
316297,1781-04-30,exame,ExamesExame privado e grau de Licenciado,"Atos grandes n.º 1, fl. 82"
316297,1781-04-30,grau,Licenciado em Cânones,"Exame privado e grau de Licenciado 30.04.1781,..."
316297,1781-04-30,grau.ano,Licenciado em Cânones.1781,"Exame privado e grau de Licenciado 30.04.1781,..."
316297,1781-05-06,exame,ExamesDoutoramento,"Atos grandes n.º 1, fl. 151"
316297,1781-05-06,grau,Doutor em Cânones,"Doutoramento 06.05.1781, Atos grandes n.º 1, f..."
316297,1781-05-06,grau.ano,Doutor em Cânones.1781,"Doutoramento 06.05.1781, Atos grandes n.º 1, f..."
316297,1781-05-06,uc-saida,1781-05-06,None
316297,1781-05-06,uc-saida.ano,1781,None
316297,2021-05-14,código-de-referência,PT/AUC/ELU/UC-AUC/B/001-001/R/005692,None
316297,2021-05-14,data-do-registo,2021-05-14,None
316297,2021-05-14,url,https://pesquisa.auc.uc.pt/details?id=316297,None
316297,2022-05-13,nota-processamento,Aviso: faculdade corrigida,Direito - Cânones para Cânones.

#### Atributos de uma pessoa numa tabela, attributos em colunas

---

#### Person attributes in a dataframe, attributes in columns

In [14]:
# Get list of people with with a certain value in a specific attribute

id = '316297'  # João Pedro Ribeiro
# id = '234295'  # Alexandre Metelo de Sousa
df = attribute_to_df(
                    the_type='uc-entrada',  # we need a base attribute
                    person_info=True,
                    more_cols=['instituta','matricula-faculdade','matricula-classe'],
                    filter_by=[id],
                    sql_echo=False)
view_cols = ['name','matricula-classe.date','matricula-classe','matricula-classe.obs']
df[view_cols].sort_values('matricula-classe.date')

,name,matricula-classe.date,matricula-classe,matricula-classe.obs
id,,,,
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1774-11-15,"Curso jurídico, 1º ano","Vol. III, L. I, fl. 20v."
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Curso jurídico, 2º ano","Vol. IV, L. I, fl. 48"
316297,João Pedro Ribeiro,1775-00-00,"Matemática, 1º ano","Vol. IV, L. 4, fl. 48"
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-08,"Matemática, 1º ano","Vol. V, L. IV, fl. 12v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1776-10-18,"Curso jurídico, 2º ano","Vol. V, L. I, fl. 35v."
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-06,"Cânones, 3º ano","Vol. VI, fl. 10"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1777-10-16,"Filosofia, 1º ano","Vol. VI, L. VI, fl. 13"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1778-10-02,"Cânones, 4º ano","Vol VII, L. 2, fl. 26"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1779-11-03,"Cânones, 5º ano","Vol. VII, L. 2, fl. 42"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"
316297,João Pedro Ribeiro,1780-11-27,"Cânones, 6º ano","Vol IX, L. 3, fl. 73"

#### Examinar potenciais duplicados

---

#### Examine potentital duplicates

In [15]:
from timelinknb.pandas import display_group_attributes
pd.set_option('display.max_rows',250)

no_show=['código-de-referência','data-do-registo','url','faculdade.ano','naturalidade.ano',
         'matricula-faculdade.ano','nome-apelido','nome-primeiro','nome-geografico.ano',
         'grau.ano','matricula-outra.ano','nome-geografico','instituta.ano']

dup_ids = ['234295','234710',]  # Alexandre Metelo de

display_group_attributes(dup_ids,
                             header_cols=['uc-entrada','naturalidade','faculdade','nome-pai'],
                             exclude_attributes=no_show,
                             sort_attributes=['date','type','value'],
                             cmap_name='Pastel1')

#### Notação Kleio

Ver [Kleio notation](README_kleio.md) [EN]

---

#### Kleio notation

See [Kleio notation](README_kleio.md)

In [5]:
from ucalumni.aluno import get_and_process_aluno
from ucalumni.mapping import map_aluno_kperson

from ucalumni.extractors import get_extractors

get_extractors()

id =  '234295'  #'316297'

aluno = get_and_process_aluno(id,db)
kaluno = map_aluno_kperson(aluno)
kleio = kaluno.to_kleio()

print(kleio)

n$Alexandre Metelo de Sousa/m/id=234295/obs="""

      Id: 234295
      Código de referência: PT/AUC/ELU/UC-AUC/B/001-001/S/010952

      Nome        : Alexandre Metelo de Sousa
      Data inicial: 1704-11-07
      Data final  : 1706-10-01
      Filiação:
      Naturalidade: Marialva
      Faculdade: Cânones

      Matrícula(s): 24.10.1705
      01.10.1706

      Instituta: 07.11.1704
  """
 atr$código-de-referência/"PT/AUC/ELU/UC-AUC/B/001-001/S/010952"/2022-06-08
 atr$data-do-registo/2022-06-08/2022-06-08
 atr$url/"http://pesquisa.auc.uc.pt/details?id=234295"/2022-06-08
 ls$uc-entrada/1704-11-07/1704-11-07
 ls$uc-saida/1706-10-01/1706-10-01
 ls$uc-entrada.ano/1704/1704-11-07
 ls$uc-saida.ano/1706/1706-10-01
 ls$nome/Alexandre Metelo de Sousa/1704-11-07
 ls$nome-primeiro/Alexandre/1704-11-07
 ls$nome-apelido/Metelo de Sousa/1704-11-07
 ls$nome-apelido/Sousa/1704-11-07
 ls$nome-geografico/Marialva/1704-11-07
 ls$nome-geografico.ano/Marialva.1704/1704-11-07
 ls$naturalidade/Marialva/1704-11-07
 ls$naturalidade.ano/Marialva.1704/1704-11-07
 ls$faculdade/Cânones/1704-11-07/obs=Cânones
 ls$faculdade.ano/Cânones.1704/1704-11-07/obs=Cânones
 ls$matricula-faculdade/Cânones/1705-10-24/obs=24.10.1705
 ls$matricula-faculdade.ano/Cânones.1705/1705-10-24/obs=24.10.1705
 ls$matricula-faculdade/Cânones/1706-10-01/obs=01.10.1706
 ls$matricula-faculdade.ano/Cânones.1706/1706-10-01/obs=01.10.1706
 ls$instituta/1704-11-07/1704-11-07/obs=07.11.1704 1704-11-07
 ls$instituta.ano/1704/1704-11-07/obs=07.11.1704 1704-11-07

#### Notação Kleio directamente da base de dados

Ver [Kleio notation](README_kleio.md) [EN]

---

#### Kleio notation directly from database

See [Kleio notation](README_kleio.md)

In [11]:
from ucalumni.config import Session
from timelink.mhk.models.person import Person

with Session(bind=db.get_engine()) as session:

    p: Person = session.query(Person).order_by(Person.id).first()
    k = p.to_kleio()
    print(p.to_kleio())

n$Manuel Barreto Cabaça/m/id=127764/obs="""

      Id: 127764
      Código de referência: PT/AUC/ELU/UC-AUC/B/001-001/C/000001

      Nome        : Manuel Barreto Cabaça
      Data inicial: 1690-10-01
      Data final  : 1697-10-01
      Filiação: Manuel Barreto
      Naturalidade: Portalegre

      Faculdade: Cânones
      Instituta:01.10.1690
      Matrícula(s): 01.10.1690
      01.10.1691
      01.10.1692
      01.10.1693
      01.10.1694
      01.10.1695
      01.10.1696
      01.10.1697

      Bacharel - 26.05.1696
      Formatura - 20.11.1697
  """
  rel$parentesco/filho/Manuel Barreto/127764-pai/1690-10-01
  rel$function-in-act/n/C/
  atr$código-de-referência/"PT/AUC/ELU/UC-AUC/B/001-001/C/000001"/2021-05-13
  atr$data-do-registo/2021-05-13/2021-05-13
  atr$url/"https://pesquisa.auc.uc.pt/details?id=127764"/2021-05-13
  ls$uc-entrada/1690-10-01/1690-10-01
  ls$uc-saida/1697-10-01/1697-10-01
  ls$uc-entrada.ano/1690/1690-10-01
  ls$uc-saida.ano/1697/1697-10-01
  ls$nome/Manuel Barreto Cabaça/1690-10-01
  ls$nome-primeiro/Manuel/1690-10-01
  ls$nome-apelido/Barreto Cabaça/1690-10-01
  ls$nome-apelido/Cabaça/1690-10-01
  ls$nome-pai/Manuel Barreto/1690-10-01
  ls$nome-geografico/Portalegre/1690-10-01
  ls$nome-geografico.ano/Portalegre.1690/1690-10-01
  ls$naturalidade/Portalegre/1690-10-01
  ls$naturalidade.ano/Portalegre.1690/1690-10-01
  ls$faculdade/Cânones/1690-10-01/obs=Cânones
  ls$faculdade.ano/Cânones.1690/1690-10-01/obs=Cânones
  ls$matricula-faculdade/Cânones/1690-10-01/obs=01.10.1690
  ls$matricula-faculdade.ano/Cânones.1690/1690-10-01/obs=01.10.1690
  ls$matricula-faculdade/Cânones/1691-10-01/obs=01.10.1691
  ls$matricula-faculdade.ano/Cânones.1691/1691-10-01/obs=01.10.1691
  ls$matricula-faculdade/Cânones/1692-10-01/obs=01.10.1692
  ls$matricula-faculdade.ano/Cânones.1692/1692-10-01/obs=01.10.1692
  ls$matricula-faculdade/Cânones/1693-10-01/obs=01.10.1693
  ls$matricula-faculdade.ano/Cânones.1693/1693-10-01/obs=01.10.1693
  ls$matricula-faculdade/Cânones/1694-10-01/obs=01.10.1694
  ls$matricula-faculdade.ano/Cânones.1694/1694-10-01/obs=01.10.1694
  ls$matricula-faculdade/Cânones/1695-10-01/obs=01.10.1695
  ls$matricula-faculdade.ano/Cânones.1695/1695-10-01/obs=01.10.1695
  ls$matricula-faculdade/Cânones/1696-10-01/obs=01.10.1696
  ls$matricula-faculdade.ano/Cânones.1696/1696-10-01/obs=01.10.1696
  ls$matricula-faculdade/Cânones/1697-10-01/obs=01.10.1697
  ls$matricula-faculdade.ano/Cânones.1697/1697-10-01/obs=01.10.1697
  ls$grau/Bacharel em Cânones/1696-05-26/obs=26.05.1696
  ls$grau.ano/Bacharel em Cânones.1696/1696-05-26/obs=26.05.1696
  ls$grau/Formatura em Cânones/1697-11-20/obs=20.11.1697
  ls$grau.ano/Formatura em Cânones.1697/1697-11-20/obs=20.11.1697
  ls$instituta/1690-10-01/1690-10-01/obs=01.10.1690 1690-10-01
  ls$instituta.ano/1690/1690-10-01/obs=01.10.1690 1690-10-01
  referido$Manuel Barreto/None/id=127764-pai

# Debug

In [5]:
import requests

kurl2 = f"{url}/rest/exports/reference_sources/varia/auc-alunos-264605-A-140337-140771.xml"

print(kurl2)
headers = {"Authorization": f"Bearer {token}"}

response = requests.get(kurl2, headers=headers)
if response.status_code == 200:
    xml_string = response.text
    print(xml_string[0:2048])
else:
    print(f"Error: {response.status_code} - {response.reason}")

http://127.0.0.1:8090/rest/exports/reference_sources/varia/auc-alunos-264605-A-140337-140771.xml
<?xml version='1.0'?>
<KLEIO STRUCTURE="/usr/local/timelink/clio/src/gacto2.str" SOURCE="/kleio-home/reference_sources/varia/auc-alunos-264605-A-140337-140771.cli" TRANSLATOR="gactoxml2.str" WHEN="2023-10-17 4:28:16" OBS="" SPACE="">
<CLASS NAME="source" SUPER="entity" TABLE="sources" GROUP="fonte">
     <ATTRIBUTE NAME="id" COLUMN="id" CLASS="id" TYPE="varchar" SIZE="64" PRECISION="0" PKEY="1" ></ATTRIBUTE>
     <ATTRIBUTE NAME="date" COLUMN="the_date" CLASS="date" TYPE="varchar" SIZE="24" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="type" COLUMN="the_type" CLASS="type" TYPE="varchar" SIZE="32" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="value" COLUMN="the_value" CLASS="value" TYPE="varchar" SIZE="254" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="loc" COLUMN="loc" CLASS="loc" TYPE="varchar" SIZE="64" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="ref" COLUMN="ref" CLASS="ref" TYPE="varchar" SIZE="64" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="kleiofile" COLUMN="kleiofile" CLASS="kleiofile" TYPE="varchar" SIZE="512" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="obs" COLUMN="obs" CLASS="obs" TYPE="varchar" SIZE="16654" PRECISION="0" PKEY="0" ></ATTRIBUTE>
     <ATTRIBUTE NAME="replace" COLUMN="replaces" CLASS="replace" TYPE="varchar" SIZE="254" PRECISION="0" PKEY="0" ></ATTRIBUTE>
</CLASS>

<GROUP ID="auc-alunos-264605-A-140337-140771" NAME="fonte" CLASS="source" ORDER="1" LEVEL="1" LINE="28">
    <ELEMENT NAME="line" CLASS="line"><core>28</core></ELEMENT>
    <ELEMENT NAME="id" CLASS="id"><core>auc-alunos-264605-A-140337-140771</core></ELEMENT>
    <ELEMENT NAME="groupname" CLASS="groupname"><core>fonte</core></ELEMENT>
   <ELEMENT NAME="inside" CLASS="inside"><core>root</core></ELEMENT>
   <ELEMENT NAME="class" CLASS="class"><core>source</core></ELEMENT>
    <ELEMENT NAME="order" CLASS="order"><core>1</core></ELEMENT>
    <ELEMENT NAME="level" CLASS="level"><core>1</core></ELEMENT>
   <ELEMENT NAME="year" CLASS="undef">

In [29]:
from timelink.kleio.importer import import_from_xml

file = "https://raw.githubusercontent.com/time-link/timelink-py/f76007cb7b98b39b22be8b70b3b2a62e7ae0c12f/tests/xml_data/b1685.xml"  # noqa

with db.session() as session:
    stats = import_from_xml(file, session=session,options={"return_stats": True})
stats

Storing 2 postponed relations

{'datetime': 1697549928.160403,
 'machine': 'jrc-air-m2.local',
 'database': sqlite:////Users/jrc/develop/timelink-py/tests/timelink-home/sources/test-project/database/sqlite/timelink.db.sqlite,
 'file': 'https://raw.githubusercontent.com/time-link/timelink-py/f76007cb7b98b39b22be8b70b3b2a62e7ae0c12f/tests/xml_data/b1685.xml',
 'import_time_seconds': 2.4436087608337402,
 'entities_processed': 747,
 'entity_rate': 305.69541735688057,
 'person_rate': 78.98154692085402,
 'nerrors': 0,
 'errors': []}